# https://espanso.org/docs/
matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":id"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          # 2022-12-04T21:45:31.049Z
          format: "%Y-%m-%dT%H:%M:%S%.3fZ"

  - trigger: ":c15"
    replace: "https://cal.com/samzanca/15min"
  - trigger: ":c30"
    replace: "https://cal.com/samzanca/30min"
