# https://espanso.org/docs/
matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
  - trigger: ":iso"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          # 2022-12-04T21:45:31.049Z
          format: "%Y-%m-%dT%H:%M:%S%.3fZ"

  - trigger: ":meta"
    replace: |
      - trigger: ":trigger"
        replace: "Nice!"

  - trigger: ":links"
    replace: "https://www.linkedin.com/in/samuele-zanca/"
  - trigger: ":links"
    replace: "https://github.com/metruzanca/"

  - trigger: ":jira"
    replace: "https://chainalysis.atlassian.net/browse/"
  - trigger: ":todo"
    replace: "TODO(samuele.zanca):"
    # Work Email
  - trigger: ":email"
    replace: "samuele.zanca@chainalysis.com"
  - trigger: ":details"
    replace: |
      <details>
      <summary></summary>

      </details>
  - trigger: ":senior"
    replace: "señor"
  - trigger: ":Senior"
    replace: "Señor"
