theme = "onedarker"
[editor]
true-color = true
# See https://twitter.com/swlkr/status/1651284505968115714
idle-timeout = 0

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

# Disable arrow keys in normal mode to force me to build muscle memory
[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# [keys.insert]
# up = "no_op"
# down = "no_op"
# left = "no_op"
# right = "no_op"
