# metruzanca

# https://github.com/Macchina-CLI/macchina/blob/main/doc/macchina.7.scd

spacing         = 2
padding         = 0
key_color       = "#6c42f5"

# If i get sick of the purple, I can use this
# [randomize]
# key_color       = true
# separator_color = true

hide_ascii = true
# prefer_small_ascii = true
[custom_ascii]
# path = "~/.config/macchina/themes/zanca.dev-ascii.txt"

[palette]
visible = true

[box]
border          = "rounded"
visible         = true
title           = " Metru 🚀 "
