# metruzanca

# https://github.com/Macchina-CLI/macchina/blob/main/doc/macchina.7.scd

spacing         = 2
padding         = 0
hide_ascii = true
key_color       = "#6c42f5"

# If i get sick of the purple, I can use this
# [randomize]
# key_color       = true
# separator_color = true

[palette]
visible = true

[box]
border          = "rounded"
visible         = true
title           = " Metru 🚀 "
